name:                Practice-Haskell
version:             0.1.0.0
github:              "Tatsuki-I/Practice-Haskell"
license:             BSD3
author:              "Tatsuki-I"
maintainer:          "tatsuki.devel@gmail.com"
copyright:           "2019 Tatsuki-I"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Development

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Tatsuki-I/Practice-Haskell#readme>

dependencies:
- base >= 4.7 && < 5
- array
- parallel
- xorshift
- mwc-random
- vector

library:
  source-dirs: src

executables:
  Practice-Haskell:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Practice-Haskell
  ParallelQSort1: 
    main:                Main.hs
    source-dirs:         app/parallel/P1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Practice-Haskell
  ParallelQSort2: 
    main:                Main.hs
    source-dirs:         app/parallel/P2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Practice-Haskell
  SerialQSort: 
    main:                Main.hs
    source-dirs:         app/parallel/Serial
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Practice-Haskell

tests:
  Practice-Haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Practice-Haskell
